
services:
  mysql:
    image: 'mysql:8.0'
    working_dir: /application
    volumes:
      - '.:/application'
      - ./php-fpm/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mvcdocker
    ports:
      - '3306'
  webserver:
    image: 'nginx:alpine'
    working_dir: /application
    volumes:
      - '.:/application'
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8000:80'
  php-fpm:
      build: ./php-fpm
      working_dir: /application
      volumes:
          - '.:/application'
          - './php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
          - './php-fpm/php-ini-overrides.ini:/etc/php/8.1/cli/conf.d/99-overrides.ini'

